'use client';
import '@btechlabs/fiber-styles/index.css';
import Link from 'next/link';
import { ReactNode } from 'react';
import './global.css';
import { demos } from './routes';
import { usePathname } from 'next/navigation';
import { useRouter } from 'next/router';
import { en, ar } from '../../../libs/shared/constants/consts';

export const metadata = {
  title: 'Welcome to blue-beetle-web',
  description: 'Generated by create-nx-workspace',
};

export default function Layout({ children }: { children: ReactNode }) {
  const pathname = usePathname();
  const router = useRouter();
  const lang = router.locale || ar;

  const langString = Array.isArray(lang) ? lang[0] : lang || en;
  return (
    <>
      <nav>
        <ul>
          {demos.map((demo) => (
            <li
              key={demo.path}
              className={demo.path === pathname ? 'active' : ''}
            >
              <Link href={demo.path.replace('[lang]', langString)}>
                {demo.name}
              </Link>
            </li>
          ))}
        </ul>
      </nav>
      <main>{children}</main>
    </>
  );
}
